# Generated by Django 6.1 on 2026-09-03 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('slug', models.SlugField(help_text='주소에 쓰이는 영문 조각. 한글 자동변환은 안 되니 직접 영문으로 입력.', max_length=200, unique=True, verbose_name='URL 조각')),
                ('category', models.CharField(choices=[('event', '이벤트'), ('update', '업데이트'), ('cashshop', '캐시샵'), ('coupon', '쿠폰')], max_length=20, verbose_name='카테고리')),
                ('start_at', models.DateTimeField(verbose_name='시작 일시')),
                ('end_at', models.DateTimeField(blank=True, help_text='종료일 없는 상시 이벤트는 비워둡니다.', null=True, verbose_name='종료 일시')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/', verbose_name='썸네일')),
                ('summary_short', models.CharField(help_text='목록 카드에 보이는 한 줄.', max_length=255, verbose_name='한 줄 요약')),
                ('summary_three', models.TextField(help_text='줄바꿈으로 구분. 두 줄이나 네 줄이 될 수도 있음.', verbose_name='3줄 요약')),
                ('body', models.TextField(blank=True, help_text="마크다운. 비우면 '상세히 보기' 버튼이 숨겨집니다.", verbose_name='상세 본문')),
                ('source_url', models.URLField(blank=True, verbose_name='원문 링크')),
                ('is_published', models.BooleanField(default=False, verbose_name='발행')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '이벤트',
                'verbose_name_plural': '이벤트',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='보상 이름')),
                ('quantity', models.CharField(blank=True, max_length=100, verbose_name='수량')),
                ('condition', models.CharField(blank=True, max_length=255, verbose_name='획득 조건')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='events.event', verbose_name='이벤트')),
            ],
            options={
                'verbose_name': '보상',
                'verbose_name_plural': '보상',
                'ordering': ['order'],
            },
        ),
    ]
