# Generated by Django 6.1 on 2026-09-04 08:01

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body',
            field=markdownx.models.MarkdownxField(blank=True, help_text="마크다운. 이미지는 칸으로 끌어다 놓으면 자동 업로드됩니다. 비우면 '상세히 보기' 버튼이 숨겨집니다.", verbose_name='상세 본문'),
        ),
    ]
