# Generated by Django 6.1 on 2026-09-04 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body',
            field=models.TextField(blank=True, help_text="마크다운. 이미지는 아래 '본문 이미지'에 올린 뒤 생성된 코드를 붙여넣으세요. 비우면 '상세히 보기' 버튼이 숨겨집니다.", verbose_name='상세 본문'),
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='body/', verbose_name='이미지')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='설명(선택)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.event', verbose_name='이벤트')),
            ],
            options={
                'verbose_name': '본문 이미지',
                'verbose_name_plural': '본문 이미지',
            },
        ),
    ]
