# Generated by Django 6.1 on 2026-09-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_body_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body',
            field=models.TextField(blank=True, help_text="마크다운. 비우면 '상세히 보기' 버튼이 숨겨집니다.", verbose_name='상세 본문'),
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
